/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.8.3/userguide/multi_project_builds.html
 */

pluginManagement {
    plugins {
        id("pt.branden.brandenportal.greeting") version "0.1.0"
    }

    val repoPath = java.nio.file.Paths.get(settings.rootDir.absolutePath).resolve("local-plugin-repository")
    with(File(repoPath.toUri())) {
        if (!exists()) {
            mkdir()
        }
    }

    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            url = uri("https://repo.spring.io/milestone")
        }
        maven {
            url = uri("https://plugins.gradle.org/m2")
        }
        maven {
            url = uri("https://dl.bintray.com/konform-kt/konform")
        }
        maven {
            url = uri("https://dl.bintray.com/konform-kt/konform")
        }
        maven {
            name = "localPlugin"
            url = uri(repoPath.toUri())
        }
        jcenter()
        google()
    }
}

rootProject.name = "kotlin-standalone-gradle-plugin"
include("plugin")
