/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/custom_plugins.html
 */

import java.io.FileInputStream
import java.nio.file.Path
import java.nio.file.Paths
import java.util.Properties

version = "0.1.0"

val repoPath: Path = Paths.get(project.rootProject.projectDir.absolutePath).resolve("local-plugin-repository")
with(File(repoPath.toUri())) {
    if (!exists()) {
        mkdir()
    }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

publishing {
    repositories {
        maven {
            name = "localPluginRepository"
            url = uri(repoPath.toUri())
        }
    }
}

gradlePlugin {
    // Define the plugin
    val greeting by plugins.creating {
        id = "pt.branden.brandenportal.greeting"
        implementationClass = "pt.branden.brandenportal.KotlinStandaloneGradlePluginPlugin"
    }
}
